### ISSUE TITLE
'Write' requests should be answered with 'Write' replies

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/harp.core.rp2040#10]
When requesting a write, for example to a core register, the instruction is completed but the returned message is of 'read' instead of 'write' type.

**Comment by Poofjunior** [comment]
Hmm, I looked for where there might be a mismatch, but I don't see it. Do you remember specifically what the transactions were?

Most Harp core register replies call the `write_reg_generic` handler function, which issues a `WRITE` type reply.
https://github.com/AllenNeuralDynamics/harp.core.rp2040/blob/main/firmware/src/harp_core.cpp#L233C21-L233C21

I checked all the register-specific write functions too. They also issue `WRITE` type replies also.

**Comment by bruno-f-cruz** [comment]
I think it was a write enabling the Heartbeat bit flag in the OpReg
register (10?)

**Comment by Poofjunior** [comment]
Ohh; this might be in replying to asserting the DUMP bit. It looks like the core registers responded with WRITE replies, but the app registers responded with READ replies.

**Comment by Poofjunior** [comment]
Fixed in:
https://github.com/AllenNeuralDynamics/harp.core.rp2040/commit/c0eab2b629f45968dd49827784f307aabca934e5
